root: true

env:
  node: true
  browser: true
  es2020: true

extends:
  - eslint:recommended
  - next/core-web-vitals
  - plugin:@typescript-eslint/recommended
  - prettier

parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  project: tsconfig.json

rules:
  "@typescript-eslint/consistent-type-imports": error
  "@typescript-eslint/consistent-type-exports": error
  "@typescript-eslint/no-useless-empty-export": error
  "@typescript-eslint/explicit-function-return-type": error

  no-console: warn
